# Our tasks are all performed by depending on rpmfusion__impl (../meta/main.yml).
# The ansible output could be confusing.  Explain it to the user.
#
# If we don't specify `name`, we see task prefixed as e.g. "ping"
# instead of "rpmfusion-free" e.g. in --list-tasks; this is not helpful.
# If we use "debug" instead of "ping", we are forced to specify "msg" too.
#
- name: rpmfusion-free enabled ok
  ping:
  tags: rpmfusion
