- hosts: invalid #volcano
  roles:
    - ansible-target
  # bootstrap using raw module, do not run setup module first
  gather_facts: no

- hosts: volcano
  roles:
#    - repos-fedora
    - etckeeper

- hosts: brick
  roles:
    - etckeeper
    - openssh-server
