# Bootstrap using raw module
- hosts: all
  gather_facts: no  # do not try to run setup module first
  roles:
    - ansible-target

# fedora
- hosts: alan-laptop, alan-nuc
  roles:
    - repos-fedora
    - etckeeper

# debian
# FIXME: debian backport install of ansible,
# to version which supports package module?
- hosts: brick
  roles:
    - repos-debian-jessie
    - etckeeper

- hosts: alan-nuc
  roles:
    - openssh-server

- hosts: brick
  roles:
    - openssh-server
