---
- hosts: all
  roles:
    - ansible-target
  # bootstrap using raw module, do not run setup module first
  gather_facts: no

- hosts: volcano
  roles: 
    - fedora-repos

- hosts:
    - openssh-server
