# By automating installs with an ansible role,
# you don't see the normal click-through from the website.
#
# Fedora are currently providing a similar install method,
# so I don't expect to get any calls from Google lawyers :).

- name: LEGAL NOTICE - Google Chrome and third party Terms of Service apply
  debug:
    msg: https://www.google.com/chrome/ or read
         https://www.google.com/intl/en/chrome/browser/privacy/eula_text.html
  delegate_to: 127.0.0.1
  run_once: yes

# Signing key taken from https://www.google.com/linuxrepositories/

- name: Copy Google signing keys
  copy:
    src: '{{ item }}'
    dest: /ansible-managed/google-chrome/
  with_items:
    - linux_signing_key.pub
    - key_fingerprints.txt

- name: Copy script for checking key fingerprints
  copy:
    src: '{{ item }}'
    dest: /ansible-managed/google-chrome/

    # Ansible copy module does not preserve executable bit, unlike `cp`.
    mode: a+x
  with_items:
    - keyfile_to_fingerprints.sh

# The script requires GPG.  GPG is also needed for `apt-key add`.

- name: Install GPG for checking key fingerprints
  package:
    name: gnupg2
    state: present

# This role adds keys with specific fingerprints.
# We do not accept key updates over HTTPS, unlike google-chrome.repo.

- name: Our key file matches our list of fingerprints
  shell: |
    ./keyfile_to_fingerprints.sh linux_signing_key.pub |
    diff -u key_fingerprints.txt /dev/stdin
  args:
    chdir: /ansible-managed/google-chrome/
  changed_when: False
  check_mode: False

- name: Supported OS - must use apt or dnf (or possibly yum)
  assert:
    that: ansible_pkg_mgr in ['apt', 'dnf', 'yum']
    msg: >
      This role only supports an OS based on "Debian" or "RedHat".
      See also "ansible -m setup ... | grep ansible_os_family".

- include: setup-apt-source.yml
  when: ansible_pkg_mgr == 'apt'

- include: setup-yum-repo.yml
  when: ansible_pkg_mgr in ['yum', 'dnf']
