# Sigh.
# So I think apt_key was always showing "changed" before?
# And now apt_key is showing "changed",
# but if there was already a key,
# it decides it doesn't need to do anything.
- name: Debian - Remove stale signing key
  file:
    name: /etc/apt/trusted.gpg.d/google.gpg
    state: absent
  when: public_key.changed

- name: Debian - Import signing key
  apt_key:
    file: /ansible-managed/google-chrome/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/google.gpg
  when: public_key.changed
  register: key

# Use the standard google-chrome.list.  It points to a fixed url (CDN).
# If a local cache is desired, a proxy can be set in apt.conf.

- name: Debian - Add Google Chrome package source
  copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
  register: source

# This test is slow, only bother when changed.
# (In which case, the next use of apt would have had to do it anyway).

- name: Debian - Test "apt-get update"
  command: apt-get update
  when: key.changed or source.changed
  register: update
  failed_when: update.rc != 0 or update.stderr != ""

# Consistency check for existing installs.  Have Google done something
# "unexpected" that has left a stale, presumably insecure package?

- name: Debian - Test package is available in repo
  command: apt-get --print-uris download google-chrome-stable
  check_mode: no
  changed_when: False

- name: Debian - Install Google Chrome
  package:
    name: google-chrome-stable
    state: present
