- name: Debian - Import signing key
  apt_key:
    file: /ansible-managed/google-chrome/linux_signing_key.pub
    id: "{{ item }}"
    keyring: /etc/apt/trusted.gpg.d/google.gpg
  with_items: 
    # "Including [ids] allows check mode to correctly report the changed state"
    - 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    - EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
  register: keys

# Use the standard google-chrome.list.  It points to a fixed url (CDN).
# If a local cache is desired, a proxy can be set in apt.conf.

- name: Debian - Add Google Chrome package source
  copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
  register: source

# This test is slow, only bother when changed.
# (In which case, the next use of apt would have had to do it anyway).

- name: Debian - Test "apt-get update"
  command: apt-get update
  when: source.changed
  register: update
  failed_when: update.rc != 0 or update.stderr != ""
  args:
    warn: no  # Can't use apt module.  It doesn't detect unreachable repos.

# Consistency check for existing installs.  Have Google done something
# "unexpected" that has left a stale, presumably insecure package?

- name: Debian - Test package is available in repo
  command: apt-get --print-uris download google-chrome-stable
  args:
    warn: no  # can't use ansible apt module, it does not implement this
  check_mode: no
  changed_when: False
