- name: Debian - Import signing key
  apt_key:
    file: /ansible-managed/google-chrome/linux_signing_key.pub
    id: "{{ item }}"
    keyring: /etc/apt/trusted.gpg.d/google.gpg
  with_items: 
    # "Including this allows check mode to correctly report the changed state"
    - 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    - EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
  register: keys

# Use the standard google-chrome.list.  It points to a fixed url (CDN).
# If a local cache is desired, a proxy can be set in apt.conf.
#
- name: Debian - Add Google Chrome package source
  copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
  register: source

# This test is slow, only bother when changed.
# (In which case, the next use of apt would have had to do it anyway).
- name: Test "apt-get update"
  when: source.changed
  command: apt-get update
  register: update
  failed_when: |
    "\nErr " in ("\n" + update.stdout) or
    "\nE: "  in ("\n" + update.stderr) or
    "\nW: "  in ("\n" + update.stderr)
  args:
    warn: no  # don't use apt module, it has to update cache in check mode
