- name: Check OS is Debian
  assert:
    that: "ansible_distribution == 'Debian'"

- name: Add jessie-backports repo (UK mirror)
  copy: src=apt/ dest=/etc/apt/
  register: repos

# This test is slow, only bother when changed.
# (In which case, the next use of apt-get would probably have had to do this anyway).
- name: Test "apt-get update"
  when: repos.changed
  command: apt-get update
  args:
    warn: no  # don't use apt module, it has to update cache in check mode
