- name: Check OS is Fedora
  assert:
    that: "ansible_distribution == 'Fedora'"

- name: Configure Fedora repos using local cache
  copy: src=yum.repos.d/ dest=/etc/yum.repos.d/
  register: fedora_repos


# This test is slow, only bother when changed.
# ansible will consider this a change,
# I don't think it matters much either way.
- name: Expire repo cache
  when: fedora_repos.changed
  command: dnf clean expire-cache
  args:
    warn: no  # can't use ansible dnf module, it does not implement this

- name: Test repo access, this could take a minute or so
  when: fedora_repos.changed
  command: dnf check-update
  args:
    warn: no  # can't use ansible dnf module, it does not implement this

