- name: Check OS is Fedora
  assert:
    that: ansible_distribution == 'Fedora'

# Signing keys: https://rpmfusion.org/keys
#
# Notice RPMFusion supports secure upgrades between versions of Fedora.
# It will be possible to update this role's copy of the keys accordingly.
# Equally, if you already installed RPMFusion you could cross-check the keys.
#
- name: Copy signing keys
  copy:
    src: "{{ item }}"
    dest: /ansible-managed/rpmfusion/
  with_items:
    - rpm-gpg
    - fingerprints

# Ansible copy module does not preserve executable bit (unlike `cp`).
#
- name: Copy script for checking key fingerprints
  copy:
    src: "{{ item }}"
    dest: /ansible-managed/rpmfusion/
    mode: a+x
  with_items:
    - keyfile_to_fingerprints.sh

- name: Install gpg
  package: name=gpg state=present

# This role also includes fingerprints of the keys.
#
- name: Our key file matches our list of fingerprints
  shell: VER="{{ ansible_distribution_major_version }}";
         ./keyfile_to_fingerprints.sh rpm-gpg/*-"$VER" |
         diff -u fingerprints/*-"$VER" /dev/stdin
  args:
    chdir: /ansible-managed/rpmfusion/
  changed_when: False
  always_run: True

- name: Import signing key
  rpm_key:
    key: /ansible-managed/rpmfusion/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
    state: present

  # On F25, import succeeds but is considered failed due to noisy rpm bug.
  # https://bugzilla.redhat.com/show_bug.cgi?id=1398272#c3
  register: import_key
  until: not import_key|failed
  retries: 1
  delay: 0

- name: Download rpmfusion-free-release RPM
  get_url:
    url: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: /ansible-managed/rpmfusion/

- name: Verify rpmfusion-free-release RPM
  command: rpm --checksig rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
  args:
    chdir: /ansible-managed/rpmfusion/
    warn: no  # can't use ansible dnf module, it does not implement this
  changed_when: False

- name: Install rpmfusion-free-release RPM
  package:
    name: /ansible-managed/rpmfusion/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  register: install

# This test may be slow, only bother when changed.
# (In which case, the next use of dnf would probably have had to do this anyway).
- name: Test "dnf check-update"
  when: install.changed
  command: dnf \
           --disablerepo="*" --enablerepo=rpmfusion-free
           check-update
  register: dnf_check_update
  # exit status is 0 on success, 100 if updates available (otherwise 100)
  failed_when: dnf_check_update.rc not in [0, 100]
  args:
    warn: no  # can't use ansible dnf module, it does not implement this
