- hosts: alan-laptop
  roles:
    - repos-fedora
    - etckeeper

    # My Dell Latitude E5450 seems ok with `powertop --auto-tune`.
    #
    # except I am now debugging occasional hangs soon after resume, starting some time before 2017-01-09
    #
    #- powertop-full-override

    - packages-gui
    - google-chrome
